# Generated by Django 5.0rc1 on 2023-11-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'A Fazer'), (2, 'Fazendo'), (3, 'Concluído')])),
            ],
        ),
    ]
